### ISSUE TITLE
Can not reinstall

### ISSUE THREAD

**Issue by jr1457** [ruohki/lunchpad#6]
After installed once and working, uninstalled, and installed again the installer gets stuck.

**To Reproduce**
1. Install
2. Run for a bit
3. uninstall
4. not be able to reinstall.

**Expected behavior**
Since it worked before I believe I should be able to reinstall,

**Screenshots**
![image](https://user-images.githubusercontent.com/73543761/115160608-19365980-a067-11eb-8ca8-0b94e45969b5.png)

gets stuck here
**Desktop**
 - OS: Windows 10
 - Version 0.4.0

**Comment by ruohki** [comment]
Hmm, this is a strange one. Can you use the zip release? Its the same just without the installer that puts the app into your appdata folder. Simply put the thing anywhere and run the Lunchpad.exe. This might be windows msi installer related :(

**Comment by jr1457** [comment]
Zip release works fine on 0.4.0. (Just wanted to thank you for a very quick reply and how great this software is. It really works well other than the installer issue right now. )

**Comment by ruohki** [comment]
Ty for your kind words. Ill close this issue. For now :)
